package co.q64.arcade.base.api.container;

public enum BaseInventoryType {
	ANVIL, BEACON, BREWING, CHEST, CRAFTING, CREATIVE, DISPENSER, DROPPER, ENCHANTING, ENDER_CHEST, FURNACE, HOPPER, MERCHANT, PLAYER, SHULKER_BOX, WORKBENCH
}
